In [21]:
import numpy as np

#settings for the model
isPoly=False
isLeanear=True
PolyDegree=2
usingRegularizer=True
Lambda=0.01
W=None # current weight
def my_regression(trainX,testX,noutputs):
    ## coding here
    print(trainX.shape)
    print(testX.shape)
    print(noutputs)
    phi=None
    T=trainX[:,trainX.shape[1]-noutputs:]
    if isLeanear:
        print("Using leanear model")
        phi=trainX[:,0:trainX.shape[1]-noutputs]
    
        ones=np.ones((trainX.shape[0],1))
        phi=np.append(ones,phi,axis=1)
        print("phi=")
        print(phi)
    elif isPoly:
        print("using poly")
        phi=trainX[:,0:trainX.shape[1]-noutputs]
        for i in range(2,PolyDegree+1): 
            phi=np.append(phi,phi**i,axis=1)
        
        print("phi:\n",phi)
        ones=np.ones((trainX.shape[0],1))
        phi=np.append(ones,phi,axis=1)

    if usingRegularizer==True:
        print("using regularizer")
        W=np.dot(np.dot(np.linalg.pinv( Lambda * np.eye(phi.shape[1]) + np.dot(phi.T,phi)),phi.T),T)
    else:
        print("not using regularizer")
        W=np.dot(np.dot(np.linalg.pinv(np.dot(phi.T,phi)),phi.T),T)
    print("T=")
    print(T)
    print("W=")
    print(W)
    outputs=np.dot(phi,W)
    print("outputs=")
    print(outputs)

    return np.dot(np.append(np.ones((testX.shape[0],1)),testX,axis=1),W)

    

    

    pass




##main:


In [25]:


trainX=np.array([[1,2,4],[2,3,7],[3,4,10],[9,100,118]])
testX=np.array([[1,1],[2,2],[3,3]])
noutputs=1
isLeanear=False
isPoly=True
PolyDegree=3
testOut=my_regression(trainX,testX,noutputs)
print(testOut)

   


(4, 3)
(3, 2)
1
using poly
phi:
 [[            1             2             1             4             1
              8             1            64]
 [            2             3             4             9             8
             27            64           729]
 [            3             4             9            16            27
             64           729          4096]
 [            9           100            81         10000           729
        1000000        531441 1000000000000]]
using regularizer
T=
[[  4]
 [  7]
 [ 10]
 [118]]
W=
[[1.18000001e-22]
 [1.06198961e-21]
 [1.18000000e-20]
 [9.55800001e-21]
 [1.18000000e-18]
 [8.60220000e-20]
 [1.18000000e-16]
 [6.27100380e-17]
 [1.18000000e-10]]
outputs=
[[7.55200101e-09]
 [8.60220072e-08]
 [4.83328053e-07]
 [1.18000000e+02]]


ValueError: shapes (3,3) and (9,1) not aligned: 3 (dim 1) != 9 (dim 0)

In [18]:
data="./airfoil_self_noise.dat"
inputs=[]
with open(data) as f:
    for line in iter(f.readline,''):
        inputs.append(line.split())
inputs=np.array(inputs)
trainX=inputs[0:-1]
testX=inputs[-1:]
print(trainX.shape)
print(testX.shape)
print(testX)
testOut=my_regression(trainX,testX[:,0:-1],1)
print(testOut)
pass

(1502, 6)
(1, 6)
[['6300' '15.6' '0.1016' '39.6' '0.0528487' '104.204']]
(1502, 6)
(1, 5)
1
Using leanear model
phi=
[['1.0' '800' '0' '0.3048' '71.3' '0.00266337']
 ['1.0' '1000' '0' '0.3048' '71.3' '0.00266337']
 ['1.0' '1250' '0' '0.3048' '71.3' '0.00266337']
 ...
 ['1.0' '3150' '15.6' '0.1016' '39.6' '0.0528487']
 ['1.0' '4000' '15.6' '0.1016' '39.6' '0.0528487']
 ['1.0' '5000' '15.6' '0.1016' '39.6' '0.0528487']]
using regularizer


ValueError: data type must provide an itemsize